### ISSUE TITLE
Missing Water Collector recipe.

### ISSUE THREAD

**Issue by ghost** [jolesh/mt_de_nenio#1]
Just wanted to mention, that there is no recipe for the Water Collector.
Otherwise a really nice Mod for survival.

**Comment by jolesh** [comment]
Hej ghost.
Thanks, for letting me know. Seems like i forgot to add it. I just added a recipe.
Tell me if there is anything else, that can be improved.
![image](https://github.com/jolesh/mt_de_nenio/assets/29330125/3a4f0207-b24e-4df4-8aee-26665bf766fc)

**Comment by ghost** [comment]
The recipe works.
If there is maybe something to improve.
Maybe the textures for the water collector when ready, making the water texture an overlay, by erasing the stone part in the de_nenio_water_collector_ready.png, while the erased area in the png is made transparent, so that the water collector has one stone texture when ready, when using texture packs.
Learned the overlay stuff by putting an ^.
Example:
water_collection.lua line 49 instead of "de_nenio_water_collector_ready.png" it would be "default:stone.png^de_nenio_water_collector_ready.png".

That's only what I see code like in other Mods, that have overlays.

Same could be done with the sieve, if this works. But looking in the texture folder, that would be 13 sieve texture. >.<

**Comment by jolesh** [comment]
Hej @BlockAndPixelAge 

Thanks for your suggestion.  I just pushed a new version with overlays.  Wasn't too difficult, as I have used overlays before. I tried to also change the texture of the dirt/gravel in the sieve. But this breaks when the texture pack isn't 16x16, so I will keep the normal textures.

Tell me if you have any other surgestions.

**Comment by ghost** [comment]
The water collector when ready didn't break with overlay when the texture pack is higher then 16x16?
And are there no codes, for now, that prevent overlay breaking when texture packs isn't 16x16?

At the moment, I don't have any suggestions. 
The stuff with the textures was the only thing that I had.

**Comment by jolesh** [comment]
It is no problem to overlay a custom texture over one from a texture pack (my water over general stone). However it is more difficult to overlay a texture from a texture pack over another one from a texture pack (general dirt over general wood).

So I could only make the wood adaptive and not the dirt and gravel.

**Comment by ghost** [comment]
Well, it's important that the stone texture from the water collector and wood texture from the sieve stay the same, when ready/used. :D
